<?php

return array (
  'version' => '5.4.4',
  'title' => 'Floorplans',
  'type' => 'floorplans',
  'id' => '6048fca7a7894',
  'updated' => 1619032418,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '350',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '6065196829374c' => 
    array (
      'type' => 'column-meta',
      'label' => 'Voyager Property Code',
      'width' => '',
      'width_unit' => '%',
      'field' => 'voyager_property_code',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6065196829374c',
    ),
    '600b41d6cb7a6' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab10550e47',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a6',
    ),
    '600b41d6cb794' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Availability URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5138d7e0b',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb794',
    ),
    '600b41d6cb796' => 
    array (
      'type' => 'column-acf_field',
      'label' => '# Available',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5144d7e0c',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb796',
    ),
    '607b962c381064' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Availability date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_607b95db3077c',
      'date_format' => 'm/d/Y',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '607b962c381064',
    ),
    '607e4575ed4fe0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Video or tour URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_607e4413bc855',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '607e4575ed4fe0',
    ),
    '600b41d6cb798' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Beds',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5157d7e0e',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb798',
    ),
    '600b41d6cb799' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Baths',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5151d7e0d',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb799',
    ),
    '600b41d6cb79b' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Floorplan ID',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5183d7e10',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79b',
    ),
    '600b41d6cb79c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Has Specials',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a515fd7e0f',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79c',
    ),
    '600b41d6cb79e' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Sqft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0d850e46',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79e',
    ),
    '600b41d6cb79f' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Sqft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0ad50e43',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79f',
    ),
    '600b41d6cb7a1' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0ce50e45',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a1',
    ),
    '600b41d6cb7a2' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600aafb250e42',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a2',
    ),
    '600b41d6cb7a3' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0c050e44',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a3',
    ),
    '600b41d6cb7a5' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600aaf6750e41',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a5',
    ),
    '600b41d6cb7a8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Property Show Specials',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab11750e48',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a8',
    ),
    '60492043ac8b44' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'External Image URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60491fe331bce',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60492043ac8b44',
    ),
    '600b41d6cb7a9' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Unit Type Mapping',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab12750e49',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a9',
    ),
    '6032102c8ef75' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'wp_default',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '6032102c8ef75',
    ),
    '6032102c8ef77' => 
    array (
      'type' => 'column-date_published',
      'label' => 'Date Published',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'wp_default',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '6032102c8ef77',
    ),
    '603352fca8b438' => 
    array (
      'type' => 'column-meta',
      'label' => 'Data source',
      'width' => '',
      'width_unit' => '%',
      'field' => 'floorplan_source',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '603352fca8b438',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);