<?php

return array (
  'version' => '5.4.3',
  'title' => 'Manual entry',
  'type' => 'floorplans',
  'id' => '60490ab529970',
  'updated' => 1615834974,
  'columns' => 
  array (
    '604a6657e7ae14' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '130',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '120',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '604a6657e7ae14',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '350',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '604faf4fa28f5c' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Taxonomy',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'floorplantype',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '604faf4fa28f5c',
    ),
    '600b41d6cb794' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Availability URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5138d7e0b',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb794',
    ),
    '600b41d6cb796' => 
    array (
      'type' => 'column-acf_field',
      'label' => '# Available',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5144d7e0c',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb796',
    ),
    '600b41d6cb798' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Beds',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5157d7e0e',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb798',
    ),
    '600b41d6cb799' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Baths',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a5151d7e0d',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb799',
    ),
    '600b41d6cb79c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Has Specials',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600a515fd7e0f',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79c',
    ),
    '600b41d6cb79e' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Sqft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0d850e46',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79e',
    ),
    '600b41d6cb79f' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Sqft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0ad50e43',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79f',
    ),
    '600b41d6cb7a1' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0ce50e45',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a1',
    ),
    '600b41d6cb7a2' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600aafb250e42',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a2',
    ),
    '600b41d6cb7a3' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Minimum Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600ab0c050e44',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a3',
    ),
    '600b41d6cb7a5' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Maximum Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_600aaf6750e41',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a5',
    ),
    '6032102c8ef75' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'wp_default',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '6032102c8ef75',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);