<?php

return array (
  'version' => '5.7.1',
  'title' => 'Properties',
  'type' => 'properties',
  'id' => '6064eb7bbe8f7',
  'updated' => 1653326862,
  'columns' => 
  array (
    '606e669ec9fbe8' => 
    array (
      'type' => 'column-order',
      'label' => 'Order',
      'width' => '70',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => '606e669ec9fbe8',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    '6074b7fc5645a0' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Amenities',
      'width' => '275',
      'width_unit' => 'px',
      'taxonomy' => 'amenities',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b7fc5645a0',
    ),
    '6074b80cfeb850' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Property types',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'propertytypes',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b80cfeb850',
    ),
    '606546393f7cec' => 
    array (
      'type' => 'column-meta',
      'label' => 'Voyager Property Code',
      'width' => '',
      'width_unit' => '%',
      'field' => 'voyager_property_code',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606546393f7cec',
    ),
    '606546534353f8' => 
    array (
      'type' => 'field_6064eb41cac1a',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606546534353f8',
    ),
    '606551421d70a4' => 
    array (
      'type' => 'field_6065511852901',
      'label' => 'Property Code',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606551421d70a4',
    ),
    '6064ec16e2d0e4' => 
    array (
      'type' => 'field_6064eb10cac14',
      'label' => 'URL',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec16e2d0e4',
    ),
    '6064ebb939db24' => 
    array (
      'type' => 'field_6064eb17cac15',
      'label' => 'Description',
      'width' => '150',
      'width_unit' => 'px',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => '6064ebb939db24',
    ),
    '6064eb9a666668' => 
    array (
      'type' => 'field_6064eae3cac10',
      'label' => 'Address',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064eb9a666668',
    ),
    '6064ebb055c290' => 
    array (
      'type' => 'field_6064eaebcac11',
      'label' => 'City',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebb055c290',
    ),
    '6064ec0be9374c' => 
    array (
      'type' => 'field_6064eaf2cac12',
      'label' => 'State',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec0be9374c',
    ),
    '6064ec235851ec' => 
    array (
      'type' => 'field_6064eb00cac13',
      'label' => 'Zipcode',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec235851ec',
    ),
    '6064ebecc2d0e4' => 
    array (
      'type' => 'field_6064eb37cac19',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebecc2d0e4',
    ),
    '6064ebd3916874' => 
    array (
      'type' => 'field_6064eb2ecac18',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebd3916874',
    ),
    '6064ebcaebc6a8' => 
    array (
      'type' => 'field_6064eb20cac16',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebcaebc6a8',
    ),
    '6064ebf38d9168' => 
    array (
      'type' => 'field_6064eb25cac17',
      'label' => 'Phone',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebf38d9168',
    ),
    '607665f849374c' => 
    array (
      'type' => 'field_60766489d1c66',
      'label' => 'Pets',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '607665f849374c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);