<?php

return array (
  'version' => '5.4.3',
  'title' => 'Properties',
  'type' => 'properties',
  'id' => '6064eb7bbe8f7',
  'updated' => 1617226892,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '6064ebff6ccccc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Property Code',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb41cac1a',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebff6ccccc',
    ),
    '6064ec16e2d0e4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb10cac14',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec16e2d0e4',
    ),
    '6064ebb939db24' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb17cac15',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebb939db24',
    ),
    '6064eb9a666668' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Address',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eae3cac10',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064eb9a666668',
    ),
    '6064ebb055c290' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'City',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eaebcac11',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebb055c290',
    ),
    '6064ec0be9374c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'State',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eaf2cac12',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec0be9374c',
    ),
    '6064ec235851ec' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Zipcode',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb00cac13',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec235851ec',
    ),
    '6064ebecc2d0e4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb37cac19',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebecc2d0e4',
    ),
    '6064ebd3916874' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb2ecac18',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebd3916874',
    ),
    '6064ebcaebc6a8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb20cac16',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebcaebc6a8',
    ),
    '6064ebf38d9168' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Phone',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6064eb25cac17',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebf38d9168',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);