<?php

return array (
  'version' => '5.4.4',
  'title' => 'Neighborhoods',
  'type' => 'neighborhoods',
  'id' => '606df318a6abd',
  'updated' => 1617820658,
  'columns' => 
  array (
    '606df3201c28f4' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '120',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '110',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606df3201c28f4',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '606df33ce9fbe8' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Area',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'area',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606df33ce9fbe8',
    ),
    '606dfbeb72f1a8' => 
    array (
      'type' => 'properties_to_neighborhoods_to',
      'label' => 'Connected properties',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'name' => '606dfbeb72f1a8',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);