<?php

return array (
  'version' => '5.7.1',
  'title' => 'Manual entry',
  'type' => 'properties',
  'id' => '615f620aeffb8',
  'updated' => 1653326879,
  'columns' => 
  array (
    '615f64c42353f8' => 
    array (
      'type' => 'field_615f6486f5fe0',
      'label' => 'Images',
      'width' => '300',
      'width_unit' => 'px',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '10',
      'export' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '615f64c42353f8',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    '606546534353f8' => 
    array (
      'type' => 'field_6064eb41cac1a',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '606546534353f8',
    ),
    '6064eb9a666668' => 
    array (
      'type' => 'field_6064eae3cac10',
      'label' => 'Address',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064eb9a666668',
    ),
    '6064ebb055c290' => 
    array (
      'type' => 'field_6064eaebcac11',
      'label' => 'City',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebb055c290',
    ),
    '6064ec0be9374c' => 
    array (
      'type' => 'field_6064eaf2cac12',
      'label' => 'State',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec0be9374c',
    ),
    '6064ec235851ec' => 
    array (
      'type' => 'field_6064eb00cac13',
      'label' => 'Zipcode',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec235851ec',
    ),
    '616e33f7cac084' => 
    array (
      'type' => 'field_6064eb2ecac18',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '616e33f7cac084',
    ),
    '616e3400f91688' => 
    array (
      'type' => 'field_6064eb37cac19',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '616e3400f91688',
    ),
    '6074b80cfeb850' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Property types',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'propertytypes',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b80cfeb850',
    ),
    '6064ebb939db24' => 
    array (
      'type' => 'field_6064eb17cac15',
      'label' => 'Description',
      'width' => '150',
      'width_unit' => 'px',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => '6064ebb939db24',
    ),
    '6074b7fc5645a0' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Amenities',
      'width' => '275',
      'width_unit' => 'px',
      'taxonomy' => 'amenities',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b7fc5645a0',
    ),
    '6064ec16e2d0e4' => 
    array (
      'type' => 'field_6064eb10cac14',
      'label' => 'URL',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ec16e2d0e4',
    ),
    '6064ebcaebc6a8' => 
    array (
      'type' => 'field_6064eb20cac16',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebcaebc6a8',
    ),
    '6064ebf38d9168' => 
    array (
      'type' => 'field_6064eb25cac17',
      'label' => 'Phone',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6064ebf38d9168',
    ),
    '607665f849374c' => 
    array (
      'type' => 'field_60766489d1c66',
      'label' => 'Pets',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '607665f849374c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);