<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5fffa736dc322',
	'title' => 'Settings',
	'fields' => array(
		array(
			'key' => 'field_5fffafb0deddf',
			'label' => 'Apartment API Integrations',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fffab9b598c2',
			'label' => 'Site type',
			'name' => 'apartment_site_type',
			'type' => 'radio',
			'instructions' => 'Controls whether this site uses Neighborhoods and Properties.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'single' => 'This site is for a single property',
				'multiple' => 'This site is for multiple properties',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5fffc4e1f293c',
			'label' => 'Data sync',
			'name' => 'data_sync',
			'type' => 'radio',
			'instructions' => 'How should we sync data from an API to this site?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'nosync' => 'Do not automatically sync any API data into this site',
				'updatesync' => 'Update data on this site with data from the API. Try not to delete posts added manually or data in manually-added custom fields which can supplement the API.',
				'delete' => 'Delete all data that\'s been pulled from a third-party API.',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5fffc553f293d',
			'label' => 'Sync term',
			'name' => 'sync_term',
			'type' => 'radio',
			'instructions' => 'How often should the site automatically pull data from an API?',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fffc4e1f293c',
						'operator' => '!=',
						'value' => 'nosync',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'paused' => 'Paused',
				'daily' => 'Daily',
				'hourly' => 'Hourly',
				'continuous' => 'Every minute (only for testing, do not leave this setting enabled).',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_600a285dca256',
			'label' => 'Enabled integrations',
			'name' => 'enabled_integrations',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fffc4e1f293c',
						'operator' => '!=',
						'value' => 'nosync',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yardi' => 'Yardi/RentCafe',
				'entrata' => 'Entrata',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5fffb270c1f37',
			'label' => 'Yardi/RentCafe',
			'name' => 'yardi_integration_creds',
			'type' => 'group',
			'instructions' => 'The Yardi API does not currently allow for autodetecting property IDs. You must manually enter property ID numbers to enable syncing.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_600a285dca256',
						'operator' => '==',
						'value' => 'yardi',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5fffb4009b1af',
					'label' => 'Yardi API Key',
					'name' => 'yardi_api_key',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fffb4149b1b0',
					'label' => 'Yardi Property Code',
					'name' => 'yardi_property_code',
					'type' => 'text',
					'instructions' => 'Multiple property codes should be entered separated by commas',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. 12345th,67891th',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5fffb2cac1f38',
			'label' => 'Entrata',
			'name' => 'entrata_integration_creds',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_600a285dca256',
						'operator' => '==',
						'value' => 'entrata',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5fffb5301d62d',
					'label' => 'Entrata Username',
					'name' => 'entrata_user',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fffb5371d62e',
					'label' => 'Entrata Password',
					'name' => 'entrata_pass',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fffb5421d62f',
					'label' => 'Entrata Property ID',
					'name' => 'entrata_property_ids',
					'type' => 'text',
					'instructions' => 'If there are multiple properties to be pulled in, enter those separated by commas',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. 1234567,2345678',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5fffafe5dede1',
			'label' => 'Other Integrations',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fffb4459b1b1',
			'label' => 'Google Maps',
			'name' => 'google_maps',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5fffb4609b1b2',
					'label' => 'Google Maps API Key',
					'name' => 'google_maps_api_key',
					'type' => 'text',
					'instructions' => 'You can find the API key in the <a href="https://developers.google.com/maps/documentation/javascript/" target="_blank">Google Developer Console</a>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. urt2vF9W9GBBvrNc-z9ULXMs46C4PRNwcKtebQKTX',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5fffb22e3a541',
			'label' => 'Template',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-integration-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;